version: '3.6'

services:
  portainer:
    image: portainer:latest
    container_name: portainer
    build:
      context: ../dockerfile
      dockerfile: Dockerfile
    env_file:
      - .env
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - back
      - front

networks:
  back:
    external:
      name: back

  front:
    external:
      name: front

volumes:
  portainer:
